name: Lint

on:
  pull_request:
    branches:
      - main
      - develop
      - 'releases/*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: 檢出代碼
        uses: actions/checkout@v3

      - name: 設置 Node.js 環境
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: 安裝 pnpm
        run: npm install -g pnpm

      - name: 將 pnpm 添加到 PATH
        run: export PATH=$(npm bin -g):$PATH

      - name: 安裝依賴
        run: pnpm install

      - name: 執行 Lint
        run: pnpm run lint
